### ISSUE TITLE
Feature 8 : User can sign in using username 

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/GroupMeet#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log back in to meeting using their username

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can log back in to the meeting using their username

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 1 19 39 PM](https://user-images.githubusercontent.com/91447324/171055259-d482d2f6-c044-42e4-8273-d6fef382237f.png)

![Screen Shot 2022-05-30 at 1 19 54 PM](https://user-images.githubusercontent.com/91447324/171055281-ee762c8c-a84a-49e7-ae91-189e4bbeff1a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add state to when user is signed in or registering
- [x] change texts depending on buttons presses along with state
- [x] assign token to user when signed in
