### ISSUE TITLE
Feature 9 : User can view who is available at certain times

### ISSUE THREAD

**Issue by gabrielenciso** [gabrielenciso/GroupMeet#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view who is available at certain times

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can hover or click over right side table to view who is available with name tags and show the date and time

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-05-30 at 1 27 32 PM](https://user-images.githubusercontent.com/91447324/171055883-809b589e-0e00-4855-a7cb-5fbf34ecc94e.png)

![Screen Shot 2022-05-30 at 1 27 43 PM](https://user-images.githubusercontent.com/91447324/171055902-15580155-11b5-493a-81c1-ef1bd14f438e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] REMOVE week days option
- [x] Add overflow-x scroll to user meeting blocks 

Click on title to go back to home page
- [x] make event listener for header component
- [x] do routing for when header groupmeets is clicked
- [x] make sure forms are reset when going back
- [x] put user up to app.jsx 
- [x] when event.forms is loaded remove user and token 

Sign back in
- [x] look at react context and see how they changed button valued and strings
- [x] make a state for if user is signing in or registering
- [x] for sign back in, make a post request and look at react context for checking password, but check for user and assign token back again

Can see other users
- [x] make onHover handler on each div for groupblocks
- [x] update members registered number - make state
- [x] console log the user attributes
- [x] get all the user names for the meeting using a fetch request
- [x] on hover show the name cards on the top - get a component somewhere or make just make it honestly
- [x] have corresponding userId on the name card and if it is found in the user array in the group then make class name green
- [x] figure out how to order people who are available to who are not
- [ ]
